// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: app/tariff/config.proto

package tariff

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Window is the period a quota is measured over. Windows are aligned to the
// calendar in UTC, so a monthly quota resets at 00:00 on the first — not one
// month after whenever the user happened to first connect.
//
// A subscription that renews on its own billing day is served by leaving the
// quota LIFETIME and having the panel call ResetUsage on that day; that keeps
// the billing calendar where the billing system is, rather than duplicating it
// here.
type Window int32

const (
	Window_WINDOW_LIFETIME Window = 0
	Window_WINDOW_DAY      Window = 1
	Window_WINDOW_WEEK     Window = 2
	Window_WINDOW_MONTH    Window = 3
)

// Enum value maps for Window.
var (
	Window_name = map[int32]string{
		0: "WINDOW_LIFETIME",
		1: "WINDOW_DAY",
		2: "WINDOW_WEEK",
		3: "WINDOW_MONTH",
	}
	Window_value = map[string]int32{
		"WINDOW_LIFETIME": 0,
		"WINDOW_DAY":      1,
		"WINDOW_WEEK":     2,
		"WINDOW_MONTH":    3,
	}
)

func (x Window) Enum() *Window {
	p := new(Window)
	*p = x
	return p
}

func (x Window) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Window) Descriptor() protoreflect.EnumDescriptor {
	return file_app_tariff_config_proto_enumTypes[0].Descriptor()
}

func (Window) Type() protoreflect.EnumType {
	return &file_app_tariff_config_proto_enumTypes[0]
}

func (x Window) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Window.Descriptor instead.
func (Window) EnumDescriptor() ([]byte, []int) {
	return file_app_tariff_config_proto_rawDescGZIP(), []int{0}
}

// Action is what happens when a quota is exhausted.
type Action int32

const (
	// Emit an event and carry on. The panel decides what to do. This is the
	// default because it is the only action that cannot surprise a paying user.
	Action_ACTION_NOTIFY Action = 0
	// Fall back to throttle_bps in both directions. The user stays connected and
	// stays usable, just slowly.
	Action_ACTION_THROTTLE Action = 1
	// Refuse traffic outright: live connections start failing their next write
	// and new ones never carry data.
	Action_ACTION_BLOCK Action = 2
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0: "ACTION_NOTIFY",
		1: "ACTION_THROTTLE",
		2: "ACTION_BLOCK",
	}
	Action_value = map[string]int32{
		"ACTION_NOTIFY":   0,
		"ACTION_THROTTLE": 1,
		"ACTION_BLOCK":    2,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_app_tariff_config_proto_enumTypes[1].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_app_tariff_config_proto_enumTypes[1]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_app_tariff_config_proto_rawDescGZIP(), []int{1}
}

// EventKind labels a change worth telling the panel about, so it can react
// instead of polling.
type EventKind int32

const (
	EventKind_EVENT_UNKNOWN               EventKind = 0
	EventKind_EVENT_USER_CONNECTED        EventKind = 1
	EventKind_EVENT_USER_DISCONNECTED     EventKind = 2
	EventKind_EVENT_DEVICE_ADDED          EventKind = 3
	EventKind_EVENT_DEVICE_REMOVED        EventKind = 4
	EventKind_EVENT_DEVICE_LIMIT_HIT      EventKind = 5
	EventKind_EVENT_QUOTA_WARNING         EventKind = 6
	EventKind_EVENT_QUOTA_EXCEEDED        EventKind = 7
	EventKind_EVENT_QUOTA_RESET           EventKind = 8
	EventKind_EVENT_SERVER_QUOTA_WARNING  EventKind = 9
	EventKind_EVENT_SERVER_QUOTA_EXCEEDED EventKind = 10
	EventKind_EVENT_SERVER_QUOTA_RESET    EventKind = 11
	EventKind_EVENT_POLICY_CHANGED        EventKind = 12
	EventKind_EVENT_POLICY_REMOVED        EventKind = 13
	EventKind_EVENT_USER_EXPIRED          EventKind = 14
)

// Enum value maps for EventKind.
var (
	EventKind_name = map[int32]string{
		0:  "EVENT_UNKNOWN",
		1:  "EVENT_USER_CONNECTED",
		2:  "EVENT_USER_DISCONNECTED",
		3:  "EVENT_DEVICE_ADDED",
		4:  "EVENT_DEVICE_REMOVED",
		5:  "EVENT_DEVICE_LIMIT_HIT",
		6:  "EVENT_QUOTA_WARNING",
		7:  "EVENT_QUOTA_EXCEEDED",
		8:  "EVENT_QUOTA_RESET",
		9:  "EVENT_SERVER_QUOTA_WARNING",
		10: "EVENT_SERVER_QUOTA_EXCEEDED",
		11: "EVENT_SERVER_QUOTA_RESET",
		12: "EVENT_POLICY_CHANGED",
		13: "EVENT_POLICY_REMOVED",
		14: "EVENT_USER_EXPIRED",
	}
	EventKind_value = map[string]int32{
		"EVENT_UNKNOWN":               0,
		"EVENT_USER_CONNECTED":        1,
		"EVENT_USER_DISCONNECTED":     2,
		"EVENT_DEVICE_ADDED":          3,
		"EVENT_DEVICE_REMOVED":        4,
		"EVENT_DEVICE_LIMIT_HIT":      5,
		"EVENT_QUOTA_WARNING":         6,
		"EVENT_QUOTA_EXCEEDED":        7,
		"EVENT_QUOTA_RESET":           8,
		"EVENT_SERVER_QUOTA_WARNING":  9,
		"EVENT_SERVER_QUOTA_EXCEEDED": 10,
		"EVENT_SERVER_QUOTA_RESET":    11,
		"EVENT_POLICY_CHANGED":        12,
		"EVENT_POLICY_REMOVED":        13,
		"EVENT_USER_EXPIRED":          14,
	}
)

func (x EventKind) Enum() *EventKind {
	p := new(EventKind)
	*p = x
	return p
}

func (x EventKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventKind) Descriptor() protoreflect.EnumDescriptor {
	return file_app_tariff_config_proto_enumTypes[2].Descriptor()
}

func (EventKind) Type() protoreflect.EnumType {
	return &file_app_tariff_config_proto_enumTypes[2]
}

func (x EventKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventKind.Descriptor instead.
func (EventKind) EnumDescriptor() ([]byte, []int) {
	return file_app_tariff_config_proto_rawDescGZIP(), []int{2}
}

// Quota is a byte allowance measured over a window.
type Quota struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Which traffic counts towards it. Empty means all of the user's traffic;
	// otherwise only traffic through the inbound with this tag.
	//
	// Tagging one inbound as the full-tunnel profile and another as the
	// split-tunnel one is what lets a user carry, say, a small allowance on the
	// profile that bypasses the whitelist alongside a large overall allowance.
	InboundTag string `protobuf:"bytes,1,opt,name=inbound_tag,json=inboundTag,proto3" json:"inbound_tag,omitempty"`
	// Bytes allowed within the window, uplink and downlink summed. Zero means no
	// limit, which makes the quota a pure meter.
	LimitBytes uint64 `protobuf:"varint,2,opt,name=limit_bytes,json=limitBytes,proto3" json:"limit_bytes,omitempty"`
	Window     Window `protobuf:"varint,3,opt,name=window,proto3,enum=xray.app.tariff.Window" json:"window,omitempty"`
	Action     Action `protobuf:"varint,4,opt,name=action,proto3,enum=xray.app.tariff.Action" json:"action,omitempty"`
	// Rate to fall back to for ACTION_THROTTLE, in bytes per second. Zero uses
	// the manager's default.
	ThrottleBps uint64 `protobuf:"varint,5,opt,name=throttle_bps,json=throttleBps,proto3" json:"throttle_bps,omitempty"`
	// Fraction of limit_bytes at which a QUOTA_WARNING event fires, as a
	// percentage. Zero uses 90.
	WarnPercent   uint32 `protobuf:"varint,6,opt,name=warn_percent,json=warnPercent,proto3" json:"warn_percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Quota) Reset() {
	*x = Quota{}
	mi := &file_app_tariff_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quota) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quota) ProtoMessage() {}

func (x *Quota) ProtoReflect() protoreflect.Message {
	mi := &file_app_tariff_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quota.ProtoReflect.Descriptor instead.
func (*Quota) Descriptor() ([]byte, []int) {
	return file_app_tariff_config_proto_rawDescGZIP(), []int{0}
}

func (x *Quota) GetInboundTag() string {
	if x != nil {
		return x.InboundTag
	}
	return ""
}

func (x *Quota) GetLimitBytes() uint64 {
	if x != nil {
		return x.LimitBytes
	}
	return 0
}

func (x *Quota) GetWindow() Window {
	if x != nil {
		return x.Window
	}
	return Window_WINDOW_LIFETIME
}

func (x *Quota) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_ACTION_NOTIFY
}

func (x *Quota) GetThrottleBps() uint64 {
	if x != nil {
		return x.ThrottleBps
	}
	return 0
}

func (x *Quota) GetWarnPercent() uint32 {
	if x != nil {
		return x.WarnPercent
	}
	return 0
}

// Policy is everything the server needs to know about one user. It is keyed by
// email, which is the identity every Xray protocol agrees on.
type Policy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Email string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// Aggregate caps in bytes per second, across every device, connection and
	// protocol. Zero means unlimited.
	//
	// Bytes, not bits: 100 Mbit/s is 12500000.
	UplinkBps   uint64 `protobuf:"varint,2,opt,name=uplink_bps,json=uplinkBps,proto3" json:"uplink_bps,omitempty"`
	DownlinkBps uint64 `protobuf:"varint,3,opt,name=downlink_bps,json=downlinkBps,proto3" json:"downlink_bps,omitempty"`
	// How much of the cap one device may hold while others are active, as a
	// multiple of its equal share. Zero uses the shaper's default of 1.5.
	Overcommit float64 `protobuf:"fixed64,4,opt,name=overcommit,proto3" json:"overcommit,omitempty"`
	// Speed boost. boost_bytes is the budget; boost_refill_seconds is how long an
	// idle user takes to earn it back, which is what actually bounds the boost's
	// cost; boost_ceil_bps caps throughput while it is being spent.
	BoostBytes         uint64 `protobuf:"varint,5,opt,name=boost_bytes,json=boostBytes,proto3" json:"boost_bytes,omitempty"`
	BoostRefillSeconds int64  `protobuf:"varint,6,opt,name=boost_refill_seconds,json=boostRefillSeconds,proto3" json:"boost_refill_seconds,omitempty"`
	BoostCeilBps       uint64 `protobuf:"varint,7,opt,name=boost_ceil_bps,json=boostCeilBps,proto3" json:"boost_ceil_bps,omitempty"`
	// Concurrent devices allowed. Zero means unlimited.
	//
	// A device is a source address, which is the only device identity a stock
	// client offers. That makes the count an approximation in both directions: a
	// household behind one NAT looks like one device, and a phone moving between
	// cells briefly looks like two. device_limit_action therefore defaults to
	// NOTIFY — locking a paying user out over a cell handover is a worse failure
	// than letting a shared subscription through.
	MaxDevices        uint32   `protobuf:"varint,8,opt,name=max_devices,json=maxDevices,proto3" json:"max_devices,omitempty"`
	DeviceLimitAction Action   `protobuf:"varint,9,opt,name=device_limit_action,json=deviceLimitAction,proto3,enum=xray.app.tariff.Action" json:"device_limit_action,omitempty"`
	Quotas            []*Quota `protobuf:"bytes,10,rep,name=quotas,proto3" json:"quotas,omitempty"`
	// Unix seconds after which the user is refused. Zero means never.
	ExpiresAt int64 `protobuf:"varint,11,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// Refuse this user outright, whatever their quotas say.
	Disabled      bool `protobuf:"varint,12,opt,name=disabled,proto3" json:"disabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Policy) Reset() {
	*x = Policy{}
	mi := &file_app_tariff_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy) ProtoMessage() {}

func (x *Policy) ProtoReflect() protoreflect.Message {
	mi := &file_app_tariff_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy.ProtoReflect.Descriptor instead.
func (*Policy) Descriptor() ([]byte, []int) {
	return file_app_tariff_config_proto_rawDescGZIP(), []int{1}
}

func (x *Policy) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Policy) GetUplinkBps() uint64 {
	if x != nil {
		return x.UplinkBps
	}
	return 0
}

func (x *Policy) GetDownlinkBps() uint64 {
	if x != nil {
		return x.DownlinkBps
	}
	return 0
}

func (x *Policy) GetOvercommit() float64 {
	if x != nil {
		return x.Overcommit
	}
	return 0
}

func (x *Policy) GetBoostBytes() uint64 {
	if x != nil {
		return x.BoostBytes
	}
	return 0
}

func (x *Policy) GetBoostRefillSeconds() int64 {
	if x != nil {
		return x.BoostRefillSeconds
	}
	return 0
}

func (x *Policy) GetBoostCeilBps() uint64 {
	if x != nil {
		return x.BoostCeilBps
	}
	return 0
}

func (x *Policy) GetMaxDevices() uint32 {
	if x != nil {
		return x.MaxDevices
	}
	return 0
}

func (x *Policy) GetDeviceLimitAction() Action {
	if x != nil {
		return x.DeviceLimitAction
	}
	return Action_ACTION_NOTIFY
}

func (x *Policy) GetQuotas() []*Quota {
	if x != nil {
		return x.Quotas
	}
	return nil
}

func (x *Policy) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *Policy) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

// ServerQuota is a byte allowance for the whole server, for the case where the
// host itself is metered. It counts every user's traffic together.
type ServerQuota struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LimitBytes    uint64                 `protobuf:"varint,1,opt,name=limit_bytes,json=limitBytes,proto3" json:"limit_bytes,omitempty"`
	Window        Window                 `protobuf:"varint,2,opt,name=window,proto3,enum=xray.app.tariff.Window" json:"window,omitempty"`
	Action        Action                 `protobuf:"varint,3,opt,name=action,proto3,enum=xray.app.tariff.Action" json:"action,omitempty"`
	ThrottleBps   uint64                 `protobuf:"varint,4,opt,name=throttle_bps,json=throttleBps,proto3" json:"throttle_bps,omitempty"`
	WarnPercent   uint32                 `protobuf:"varint,5,opt,name=warn_percent,json=warnPercent,proto3" json:"warn_percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerQuota) Reset() {
	*x = ServerQuota{}
	mi := &file_app_tariff_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerQuota) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerQuota) ProtoMessage() {}

func (x *ServerQuota) ProtoReflect() protoreflect.Message {
	mi := &file_app_tariff_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerQuota.ProtoReflect.Descriptor instead.
func (*ServerQuota) Descriptor() ([]byte, []int) {
	return file_app_tariff_config_proto_rawDescGZIP(), []int{2}
}

func (x *ServerQuota) GetLimitBytes() uint64 {
	if x != nil {
		return x.LimitBytes
	}
	return 0
}

func (x *ServerQuota) GetWindow() Window {
	if x != nil {
		return x.Window
	}
	return Window_WINDOW_LIFETIME
}

func (x *ServerQuota) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_ACTION_NOTIFY
}

func (x *ServerQuota) GetThrottleBps() uint64 {
	if x != nil {
		return x.ThrottleBps
	}
	return 0
}

func (x *ServerQuota) GetWarnPercent() uint32 {
	if x != nil {
		return x.WarnPercent
	}
	return 0
}

// Device is one source of a user's traffic.
type Device struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Key       string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	FirstSeen int64                  `protobuf:"varint,2,opt,name=first_seen,json=firstSeen,proto3" json:"first_seen,omitempty"`
	LastSeen  int64                  `protobuf:"varint,3,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	// Connections currently open from it.
	Connections   uint32 `protobuf:"varint,4,opt,name=connections,proto3" json:"connections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_app_tariff_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_app_tariff_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_app_tariff_config_proto_rawDescGZIP(), []int{3}
}

func (x *Device) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Device) GetFirstSeen() int64 {
	if x != nil {
		return x.FirstSeen
	}
	return 0
}

func (x *Device) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

func (x *Device) GetConnections() uint32 {
	if x != nil {
		return x.Connections
	}
	return 0
}

// QuotaState is a quota plus how much of it has been spent.
type QuotaState struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	InboundTag string                 `protobuf:"bytes,1,opt,name=inbound_tag,json=inboundTag,proto3" json:"inbound_tag,omitempty"`
	UsedBytes  uint64                 `protobuf:"varint,2,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	LimitBytes uint64                 `protobuf:"varint,3,opt,name=limit_bytes,json=limitBytes,proto3" json:"limit_bytes,omitempty"`
	Window     Window                 `protobuf:"varint,4,opt,name=window,proto3,enum=xray.app.tariff.Window" json:"window,omitempty"`
	Action     Action                 `protobuf:"varint,5,opt,name=action,proto3,enum=xray.app.tariff.Action" json:"action,omitempty"`
	// Unix seconds. window_resets is zero for a LIFETIME window.
	WindowStarted int64 `protobuf:"varint,6,opt,name=window_started,json=windowStarted,proto3" json:"window_started,omitempty"`
	WindowResets  int64 `protobuf:"varint,7,opt,name=window_resets,json=windowResets,proto3" json:"window_resets,omitempty"`
	Exceeded      bool  `protobuf:"varint,8,opt,name=exceeded,proto3" json:"exceeded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuotaState) Reset() {
	*x = QuotaState{}
	mi := &file_app_tariff_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuotaState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuotaState) ProtoMessage() {}

func (x *QuotaState) ProtoReflect() protoreflect.Message {
	mi := &file_app_tariff_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuotaState.ProtoReflect.Descriptor instead.
func (*QuotaState) Descriptor() ([]byte, []int) {
	return file_app_tariff_config_proto_rawDescGZIP(), []int{4}
}

func (x *QuotaState) GetInboundTag() string {
	if x != nil {
		return x.InboundTag
	}
	return ""
}

func (x *QuotaState) GetUsedBytes() uint64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *QuotaState) GetLimitBytes() uint64 {
	if x != nil {
		return x.LimitBytes
	}
	return 0
}

func (x *QuotaState) GetWindow() Window {
	if x != nil {
		return x.Window
	}
	return Window_WINDOW_LIFETIME
}

func (x *QuotaState) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_ACTION_NOTIFY
}

func (x *QuotaState) GetWindowStarted() int64 {
	if x != nil {
		return x.WindowStarted
	}
	return 0
}

func (x *QuotaState) GetWindowResets() int64 {
	if x != nil {
		return x.WindowResets
	}
	return 0
}

func (x *QuotaState) GetExceeded() bool {
	if x != nil {
		return x.Exceeded
	}
	return false
}

// InboundUsage is a user's traffic through one inbound.
type InboundUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Uplink        uint64                 `protobuf:"varint,2,opt,name=uplink,proto3" json:"uplink,omitempty"`
	Downlink      uint64                 `protobuf:"varint,3,opt,name=downlink,proto3" json:"downlink,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InboundUsage) Reset() {
	*x = InboundUsage{}
	mi := &file_app_tariff_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboundUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboundUsage) ProtoMessage() {}

func (x *InboundUsage) ProtoReflect() protoreflect.Message {
	mi := &file_app_tariff_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboundUsage.ProtoReflect.Descriptor instead.
func (*InboundUsage) Descriptor() ([]byte, []int) {
	return file_app_tariff_config_proto_rawDescGZIP(), []int{5}
}

func (x *InboundUsage) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *InboundUsage) GetUplink() uint64 {
	if x != nil {
		return x.Uplink
	}
	return 0
}

func (x *InboundUsage) GetDownlink() uint64 {
	if x != nil {
		return x.Downlink
	}
	return 0
}

// Usage is everything the server knows about what a user has spent.
//
// These counters are the manager's own, deliberately not Xray's stats
// counters: a panel calling QueryStats with reset=true would otherwise wipe the
// numbers a monthly quota is enforced from.
type Usage struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Email    string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Uplink   uint64                 `protobuf:"varint,2,opt,name=uplink,proto3" json:"uplink,omitempty"`
	Downlink uint64                 `protobuf:"varint,3,opt,name=downlink,proto3" json:"downlink,omitempty"`
	Inbounds []*InboundUsage        `protobuf:"bytes,4,rep,name=inbounds,proto3" json:"inbounds,omitempty"`
	Devices  []*Device              `protobuf:"bytes,5,rep,name=devices,proto3" json:"devices,omitempty"`
	Quotas   []*QuotaState          `protobuf:"bytes,6,rep,name=quotas,proto3" json:"quotas,omitempty"`
	// Connections currently open.
	Connections uint32 `protobuf:"varint,7,opt,name=connections,proto3" json:"connections,omitempty"`
	// Effective caps right now, after quotas and expiry have been applied. Zero
	// means unlimited; both zero with blocked set means refused.
	EffectiveUplinkBps   uint64 `protobuf:"varint,8,opt,name=effective_uplink_bps,json=effectiveUplinkBps,proto3" json:"effective_uplink_bps,omitempty"`
	EffectiveDownlinkBps uint64 `protobuf:"varint,9,opt,name=effective_downlink_bps,json=effectiveDownlinkBps,proto3" json:"effective_downlink_bps,omitempty"`
	Blocked              bool   `protobuf:"varint,10,opt,name=blocked,proto3" json:"blocked,omitempty"`
	BlockedReason        string `protobuf:"bytes,11,opt,name=blocked_reason,json=blockedReason,proto3" json:"blocked_reason,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_app_tariff_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_app_tariff_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_app_tariff_config_proto_rawDescGZIP(), []int{6}
}

func (x *Usage) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Usage) GetUplink() uint64 {
	if x != nil {
		return x.Uplink
	}
	return 0
}

func (x *Usage) GetDownlink() uint64 {
	if x != nil {
		return x.Downlink
	}
	return 0
}

func (x *Usage) GetInbounds() []*InboundUsage {
	if x != nil {
		return x.Inbounds
	}
	return nil
}

func (x *Usage) GetDevices() []*Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

func (x *Usage) GetQuotas() []*QuotaState {
	if x != nil {
		return x.Quotas
	}
	return nil
}

func (x *Usage) GetConnections() uint32 {
	if x != nil {
		return x.Connections
	}
	return 0
}

func (x *Usage) GetEffectiveUplinkBps() uint64 {
	if x != nil {
		return x.EffectiveUplinkBps
	}
	return 0
}

func (x *Usage) GetEffectiveDownlinkBps() uint64 {
	if x != nil {
		return x.EffectiveDownlinkBps
	}
	return 0
}

func (x *Usage) GetBlocked() bool {
	if x != nil {
		return x.Blocked
	}
	return false
}

func (x *Usage) GetBlockedReason() string {
	if x != nil {
		return x.BlockedReason
	}
	return ""
}

// Event is one such change.
type Event struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	UnixNano   int64                  `protobuf:"varint,1,opt,name=unix_nano,json=unixNano,proto3" json:"unix_nano,omitempty"`
	Kind       EventKind              `protobuf:"varint,2,opt,name=kind,proto3,enum=xray.app.tariff.EventKind" json:"kind,omitempty"`
	Email      string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	InboundTag string                 `protobuf:"bytes,4,opt,name=inbound_tag,json=inboundTag,proto3" json:"inbound_tag,omitempty"`
	Device     string                 `protobuf:"bytes,5,opt,name=device,proto3" json:"device,omitempty"`
	// Bytes for quota events, a count for device events, zero otherwise.
	Value         uint64 `protobuf:"varint,6,opt,name=value,proto3" json:"value,omitempty"`
	Limit         uint64 `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	Detail        string `protobuf:"bytes,8,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_app_tariff_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_app_tariff_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_app_tariff_config_proto_rawDescGZIP(), []int{7}
}

func (x *Event) GetUnixNano() int64 {
	if x != nil {
		return x.UnixNano
	}
	return 0
}

func (x *Event) GetKind() EventKind {
	if x != nil {
		return x.Kind
	}
	return EventKind_EVENT_UNKNOWN
}

func (x *Event) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Event) GetInboundTag() string {
	if x != nil {
		return x.InboundTag
	}
	return ""
}

func (x *Event) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *Event) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Event) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Event) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

// QuotaSpent is one quota's terms plus what has been spent against them,
// persisted so that a restart does not hand every user a fresh allowance. The
// terms travel with the counter because they are what identifies it: a quota
// whose terms changed while the server was down is a different allowance, and
// its spent bytes are dropped rather than applied to it.
type QuotaSpent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *Quota                 `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	Used          uint64                 `protobuf:"varint,2,opt,name=used,proto3" json:"used,omitempty"`
	WindowStarted int64                  `protobuf:"varint,3,opt,name=window_started,json=windowStarted,proto3" json:"window_started,omitempty"`
	Exceeded      bool                   `protobuf:"varint,4,opt,name=exceeded,proto3" json:"exceeded,omitempty"`
	Warned        bool                   `protobuf:"varint,5,opt,name=warned,proto3" json:"warned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuotaSpent) Reset() {
	*x = QuotaSpent{}
	mi := &file_app_tariff_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuotaSpent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuotaSpent) ProtoMessage() {}

func (x *QuotaSpent) ProtoReflect() protoreflect.Message {
	mi := &file_app_tariff_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuotaSpent.ProtoReflect.Descriptor instead.
func (*QuotaSpent) Descriptor() ([]byte, []int) {
	return file_app_tariff_config_proto_rawDescGZIP(), []int{8}
}

func (x *QuotaSpent) GetSpec() *Quota {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *QuotaSpent) GetUsed() uint64 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *QuotaSpent) GetWindowStarted() int64 {
	if x != nil {
		return x.WindowStarted
	}
	return 0
}

func (x *QuotaSpent) GetExceeded() bool {
	if x != nil {
		return x.Exceeded
	}
	return false
}

func (x *QuotaSpent) GetWarned() bool {
	if x != nil {
		return x.Warned
	}
	return false
}

// UserState is one user's persisted policy and counters.
//
// Devices are deliberately absent: the only thing they are enforced on is how
// many are connected at once, which is zero after a restart anyway, and
// persisting them would resurrect addresses nobody is using.
type UserState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policy        *Policy                `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	Uplink        uint64                 `protobuf:"varint,2,opt,name=uplink,proto3" json:"uplink,omitempty"`
	Downlink      uint64                 `protobuf:"varint,3,opt,name=downlink,proto3" json:"downlink,omitempty"`
	Inbounds      []*InboundUsage        `protobuf:"bytes,4,rep,name=inbounds,proto3" json:"inbounds,omitempty"`
	Quotas        []*QuotaSpent          `protobuf:"bytes,5,rep,name=quotas,proto3" json:"quotas,omitempty"`
	LastSeen      int64                  `protobuf:"varint,6,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserState) Reset() {
	*x = UserState{}
	mi := &file_app_tariff_config_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserState) ProtoMessage() {}

func (x *UserState) ProtoReflect() protoreflect.Message {
	mi := &file_app_tariff_config_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserState.ProtoReflect.Descriptor instead.
func (*UserState) Descriptor() ([]byte, []int) {
	return file_app_tariff_config_proto_rawDescGZIP(), []int{9}
}

func (x *UserState) GetPolicy() *Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *UserState) GetUplink() uint64 {
	if x != nil {
		return x.Uplink
	}
	return 0
}

func (x *UserState) GetDownlink() uint64 {
	if x != nil {
		return x.Downlink
	}
	return 0
}

func (x *UserState) GetInbounds() []*InboundUsage {
	if x != nil {
		return x.Inbounds
	}
	return nil
}

func (x *UserState) GetQuotas() []*QuotaSpent {
	if x != nil {
		return x.Quotas
	}
	return nil
}

func (x *UserState) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

// State is what the manager writes to disk.
type State struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Version             int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	SavedAt             int64                  `protobuf:"varint,2,opt,name=saved_at,json=savedAt,proto3" json:"saved_at,omitempty"`
	Config              *Config                `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	Users               map[string]*UserState  `protobuf:"bytes,4,rep,name=users,proto3" json:"users,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ServerUsed          uint64                 `protobuf:"varint,5,opt,name=server_used,json=serverUsed,proto3" json:"server_used,omitempty"`
	ServerWindowStarted int64                  `protobuf:"varint,6,opt,name=server_window_started,json=serverWindowStarted,proto3" json:"server_window_started,omitempty"`
	ServerExceeded      bool                   `protobuf:"varint,7,opt,name=server_exceeded,json=serverExceeded,proto3" json:"server_exceeded,omitempty"`
	ServerWarned        bool                   `protobuf:"varint,8,opt,name=server_warned,json=serverWarned,proto3" json:"server_warned,omitempty"`
	// The allowance actually in force, which a panel may have changed since the
	// config was last written.
	ServerQuota   *ServerQuota `protobuf:"bytes,9,opt,name=server_quota,json=serverQuota,proto3" json:"server_quota,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *State) Reset() {
	*x = State{}
	mi := &file_app_tariff_config_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_app_tariff_config_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_app_tariff_config_proto_rawDescGZIP(), []int{10}
}

func (x *State) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *State) GetSavedAt() int64 {
	if x != nil {
		return x.SavedAt
	}
	return 0
}

func (x *State) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *State) GetUsers() map[string]*UserState {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *State) GetServerUsed() uint64 {
	if x != nil {
		return x.ServerUsed
	}
	return 0
}

func (x *State) GetServerWindowStarted() int64 {
	if x != nil {
		return x.ServerWindowStarted
	}
	return 0
}

func (x *State) GetServerExceeded() bool {
	if x != nil {
		return x.ServerExceeded
	}
	return false
}

func (x *State) GetServerWarned() bool {
	if x != nil {
		return x.ServerWarned
	}
	return false
}

func (x *State) GetServerQuota() *ServerQuota {
	if x != nil {
		return x.ServerQuota
	}
	return nil
}

// Config configures the tariff manager.
type Config struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Where the manager writes its state so that usage survives a restart. Empty
	// disables persistence, which means a restart forgets how much of a monthly
	// quota has been spent.
	StatePath string `protobuf:"bytes,1,opt,name=state_path,json=statePath,proto3" json:"state_path,omitempty"`
	// How often a dirty state is flushed, in seconds. Zero uses 10.
	FlushSeconds int64 `protobuf:"varint,2,opt,name=flush_seconds,json=flushSeconds,proto3" json:"flush_seconds,omitempty"`
	// Policy applied to a user with none of their own. Its email is ignored.
	DefaultPolicy *Policy      `protobuf:"bytes,3,opt,name=default_policy,json=defaultPolicy,proto3" json:"default_policy,omitempty"`
	ServerQuota   *ServerQuota `protobuf:"bytes,4,opt,name=server_quota,json=serverQuota,proto3" json:"server_quota,omitempty"`
	// Rate an ACTION_THROTTLE falls back to when the quota does not name one, in
	// bytes per second. Zero uses 131072 (1 Mbit/s).
	DefaultThrottleBps uint64 `protobuf:"varint,5,opt,name=default_throttle_bps,json=defaultThrottleBps,proto3" json:"default_throttle_bps,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_app_tariff_config_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_app_tariff_config_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_app_tariff_config_proto_rawDescGZIP(), []int{11}
}

func (x *Config) GetStatePath() string {
	if x != nil {
		return x.StatePath
	}
	return ""
}

func (x *Config) GetFlushSeconds() int64 {
	if x != nil {
		return x.FlushSeconds
	}
	return 0
}

func (x *Config) GetDefaultPolicy() *Policy {
	if x != nil {
		return x.DefaultPolicy
	}
	return nil
}

func (x *Config) GetServerQuota() *ServerQuota {
	if x != nil {
		return x.ServerQuota
	}
	return nil
}

func (x *Config) GetDefaultThrottleBps() uint64 {
	if x != nil {
		return x.DefaultThrottleBps
	}
	return 0
}

var File_app_tariff_config_proto protoreflect.FileDescriptor

const file_app_tariff_config_proto_rawDesc = "" +
	"\n" +
	"\x17app/tariff/config.proto\x12\x0fxray.app.tariff\"\xf1\x01\n" +
	"\x05Quota\x12\x1f\n" +
	"\vinbound_tag\x18\x01 \x01(\tR\n" +
	"inboundTag\x12\x1f\n" +
	"\vlimit_bytes\x18\x02 \x01(\x04R\n" +
	"limitBytes\x12/\n" +
	"\x06window\x18\x03 \x01(\x0e2\x17.xray.app.tariff.WindowR\x06window\x12/\n" +
	"\x06action\x18\x04 \x01(\x0e2\x17.xray.app.tariff.ActionR\x06action\x12!\n" +
	"\fthrottle_bps\x18\x05 \x01(\x04R\vthrottleBps\x12!\n" +
	"\fwarn_percent\x18\x06 \x01(\rR\vwarnPercent\"\xce\x03\n" +
	"\x06Policy\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"uplink_bps\x18\x02 \x01(\x04R\tuplinkBps\x12!\n" +
	"\fdownlink_bps\x18\x03 \x01(\x04R\vdownlinkBps\x12\x1e\n" +
	"\n" +
	"overcommit\x18\x04 \x01(\x01R\n" +
	"overcommit\x12\x1f\n" +
	"\vboost_bytes\x18\x05 \x01(\x04R\n" +
	"boostBytes\x120\n" +
	"\x14boost_refill_seconds\x18\x06 \x01(\x03R\x12boostRefillSeconds\x12$\n" +
	"\x0eboost_ceil_bps\x18\a \x01(\x04R\fboostCeilBps\x12\x1f\n" +
	"\vmax_devices\x18\b \x01(\rR\n" +
	"maxDevices\x12G\n" +
	"\x13device_limit_action\x18\t \x01(\x0e2\x17.xray.app.tariff.ActionR\x11deviceLimitAction\x12.\n" +
	"\x06quotas\x18\n" +
	" \x03(\v2\x16.xray.app.tariff.QuotaR\x06quotas\x12\x1d\n" +
	"\n" +
	"expires_at\x18\v \x01(\x03R\texpiresAt\x12\x1a\n" +
	"\bdisabled\x18\f \x01(\bR\bdisabled\"\xd6\x01\n" +
	"\vServerQuota\x12\x1f\n" +
	"\vlimit_bytes\x18\x01 \x01(\x04R\n" +
	"limitBytes\x12/\n" +
	"\x06window\x18\x02 \x01(\x0e2\x17.xray.app.tariff.WindowR\x06window\x12/\n" +
	"\x06action\x18\x03 \x01(\x0e2\x17.xray.app.tariff.ActionR\x06action\x12!\n" +
	"\fthrottle_bps\x18\x04 \x01(\x04R\vthrottleBps\x12!\n" +
	"\fwarn_percent\x18\x05 \x01(\rR\vwarnPercent\"x\n" +
	"\x06Device\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1d\n" +
	"\n" +
	"first_seen\x18\x02 \x01(\x03R\tfirstSeen\x12\x1b\n" +
	"\tlast_seen\x18\x03 \x01(\x03R\blastSeen\x12 \n" +
	"\vconnections\x18\x04 \x01(\rR\vconnections\"\xb7\x02\n" +
	"\n" +
	"QuotaState\x12\x1f\n" +
	"\vinbound_tag\x18\x01 \x01(\tR\n" +
	"inboundTag\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x02 \x01(\x04R\tusedBytes\x12\x1f\n" +
	"\vlimit_bytes\x18\x03 \x01(\x04R\n" +
	"limitBytes\x12/\n" +
	"\x06window\x18\x04 \x01(\x0e2\x17.xray.app.tariff.WindowR\x06window\x12/\n" +
	"\x06action\x18\x05 \x01(\x0e2\x17.xray.app.tariff.ActionR\x06action\x12%\n" +
	"\x0ewindow_started\x18\x06 \x01(\x03R\rwindowStarted\x12#\n" +
	"\rwindow_resets\x18\a \x01(\x03R\fwindowResets\x12\x1a\n" +
	"\bexceeded\x18\b \x01(\bR\bexceeded\"T\n" +
	"\fInboundUsage\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x16\n" +
	"\x06uplink\x18\x02 \x01(\x04R\x06uplink\x12\x1a\n" +
	"\bdownlink\x18\x03 \x01(\x04R\bdownlink\"\xbf\x03\n" +
	"\x05Usage\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x16\n" +
	"\x06uplink\x18\x02 \x01(\x04R\x06uplink\x12\x1a\n" +
	"\bdownlink\x18\x03 \x01(\x04R\bdownlink\x129\n" +
	"\binbounds\x18\x04 \x03(\v2\x1d.xray.app.tariff.InboundUsageR\binbounds\x121\n" +
	"\adevices\x18\x05 \x03(\v2\x17.xray.app.tariff.DeviceR\adevices\x123\n" +
	"\x06quotas\x18\x06 \x03(\v2\x1b.xray.app.tariff.QuotaStateR\x06quotas\x12 \n" +
	"\vconnections\x18\a \x01(\rR\vconnections\x120\n" +
	"\x14effective_uplink_bps\x18\b \x01(\x04R\x12effectiveUplinkBps\x124\n" +
	"\x16effective_downlink_bps\x18\t \x01(\x04R\x14effectiveDownlinkBps\x12\x18\n" +
	"\ablocked\x18\n" +
	" \x01(\bR\ablocked\x12%\n" +
	"\x0eblocked_reason\x18\v \x01(\tR\rblockedReason\"\xe7\x01\n" +
	"\x05Event\x12\x1b\n" +
	"\tunix_nano\x18\x01 \x01(\x03R\bunixNano\x12.\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x1a.xray.app.tariff.EventKindR\x04kind\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1f\n" +
	"\vinbound_tag\x18\x04 \x01(\tR\n" +
	"inboundTag\x12\x16\n" +
	"\x06device\x18\x05 \x01(\tR\x06device\x12\x14\n" +
	"\x05value\x18\x06 \x01(\x04R\x05value\x12\x14\n" +
	"\x05limit\x18\a \x01(\x04R\x05limit\x12\x16\n" +
	"\x06detail\x18\b \x01(\tR\x06detail\"\xa7\x01\n" +
	"\n" +
	"QuotaSpent\x12*\n" +
	"\x04spec\x18\x01 \x01(\v2\x16.xray.app.tariff.QuotaR\x04spec\x12\x12\n" +
	"\x04used\x18\x02 \x01(\x04R\x04used\x12%\n" +
	"\x0ewindow_started\x18\x03 \x01(\x03R\rwindowStarted\x12\x1a\n" +
	"\bexceeded\x18\x04 \x01(\bR\bexceeded\x12\x16\n" +
	"\x06warned\x18\x05 \x01(\bR\x06warned\"\xfd\x01\n" +
	"\tUserState\x12/\n" +
	"\x06policy\x18\x01 \x01(\v2\x17.xray.app.tariff.PolicyR\x06policy\x12\x16\n" +
	"\x06uplink\x18\x02 \x01(\x04R\x06uplink\x12\x1a\n" +
	"\bdownlink\x18\x03 \x01(\x04R\bdownlink\x129\n" +
	"\binbounds\x18\x04 \x03(\v2\x1d.xray.app.tariff.InboundUsageR\binbounds\x123\n" +
	"\x06quotas\x18\x05 \x03(\v2\x1b.xray.app.tariff.QuotaSpentR\x06quotas\x12\x1b\n" +
	"\tlast_seen\x18\x06 \x01(\x03R\blastSeen\"\xe0\x03\n" +
	"\x05State\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x12\x19\n" +
	"\bsaved_at\x18\x02 \x01(\x03R\asavedAt\x12/\n" +
	"\x06config\x18\x03 \x01(\v2\x17.xray.app.tariff.ConfigR\x06config\x127\n" +
	"\x05users\x18\x04 \x03(\v2!.xray.app.tariff.State.UsersEntryR\x05users\x12\x1f\n" +
	"\vserver_used\x18\x05 \x01(\x04R\n" +
	"serverUsed\x122\n" +
	"\x15server_window_started\x18\x06 \x01(\x03R\x13serverWindowStarted\x12'\n" +
	"\x0fserver_exceeded\x18\a \x01(\bR\x0eserverExceeded\x12#\n" +
	"\rserver_warned\x18\b \x01(\bR\fserverWarned\x12?\n" +
	"\fserver_quota\x18\t \x01(\v2\x1c.xray.app.tariff.ServerQuotaR\vserverQuota\x1aT\n" +
	"\n" +
	"UsersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.xray.app.tariff.UserStateR\x05value:\x028\x01\"\xff\x01\n" +
	"\x06Config\x12\x1d\n" +
	"\n" +
	"state_path\x18\x01 \x01(\tR\tstatePath\x12#\n" +
	"\rflush_seconds\x18\x02 \x01(\x03R\fflushSeconds\x12>\n" +
	"\x0edefault_policy\x18\x03 \x01(\v2\x17.xray.app.tariff.PolicyR\rdefaultPolicy\x12?\n" +
	"\fserver_quota\x18\x04 \x01(\v2\x1c.xray.app.tariff.ServerQuotaR\vserverQuota\x120\n" +
	"\x14default_throttle_bps\x18\x05 \x01(\x04R\x12defaultThrottleBps*P\n" +
	"\x06Window\x12\x13\n" +
	"\x0fWINDOW_LIFETIME\x10\x00\x12\x0e\n" +
	"\n" +
	"WINDOW_DAY\x10\x01\x12\x0f\n" +
	"\vWINDOW_WEEK\x10\x02\x12\x10\n" +
	"\fWINDOW_MONTH\x10\x03*B\n" +
	"\x06Action\x12\x11\n" +
	"\rACTION_NOTIFY\x10\x00\x12\x13\n" +
	"\x0fACTION_THROTTLE\x10\x01\x12\x10\n" +
	"\fACTION_BLOCK\x10\x02*\x98\x03\n" +
	"\tEventKind\x12\x11\n" +
	"\rEVENT_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14EVENT_USER_CONNECTED\x10\x01\x12\x1b\n" +
	"\x17EVENT_USER_DISCONNECTED\x10\x02\x12\x16\n" +
	"\x12EVENT_DEVICE_ADDED\x10\x03\x12\x18\n" +
	"\x14EVENT_DEVICE_REMOVED\x10\x04\x12\x1a\n" +
	"\x16EVENT_DEVICE_LIMIT_HIT\x10\x05\x12\x17\n" +
	"\x13EVENT_QUOTA_WARNING\x10\x06\x12\x18\n" +
	"\x14EVENT_QUOTA_EXCEEDED\x10\a\x12\x15\n" +
	"\x11EVENT_QUOTA_RESET\x10\b\x12\x1e\n" +
	"\x1aEVENT_SERVER_QUOTA_WARNING\x10\t\x12\x1f\n" +
	"\x1bEVENT_SERVER_QUOTA_EXCEEDED\x10\n" +
	"\x12\x1c\n" +
	"\x18EVENT_SERVER_QUOTA_RESET\x10\v\x12\x18\n" +
	"\x14EVENT_POLICY_CHANGED\x10\f\x12\x18\n" +
	"\x14EVENT_POLICY_REMOVED\x10\r\x12\x16\n" +
	"\x12EVENT_USER_EXPIRED\x10\x0eBO\n" +
	"\x13com.xray.app.tariffP\x01Z$github.com/xtls/xray-core/app/tariff\xaa\x02\x0fXray.App.Tariffb\x06proto3"

var (
	file_app_tariff_config_proto_rawDescOnce sync.Once
	file_app_tariff_config_proto_rawDescData []byte
)

func file_app_tariff_config_proto_rawDescGZIP() []byte {
	file_app_tariff_config_proto_rawDescOnce.Do(func() {
		file_app_tariff_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_tariff_config_proto_rawDesc), len(file_app_tariff_config_proto_rawDesc)))
	})
	return file_app_tariff_config_proto_rawDescData
}

var file_app_tariff_config_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_app_tariff_config_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_app_tariff_config_proto_goTypes = []any{
	(Window)(0),          // 0: xray.app.tariff.Window
	(Action)(0),          // 1: xray.app.tariff.Action
	(EventKind)(0),       // 2: xray.app.tariff.EventKind
	(*Quota)(nil),        // 3: xray.app.tariff.Quota
	(*Policy)(nil),       // 4: xray.app.tariff.Policy
	(*ServerQuota)(nil),  // 5: xray.app.tariff.ServerQuota
	(*Device)(nil),       // 6: xray.app.tariff.Device
	(*QuotaState)(nil),   // 7: xray.app.tariff.QuotaState
	(*InboundUsage)(nil), // 8: xray.app.tariff.InboundUsage
	(*Usage)(nil),        // 9: xray.app.tariff.Usage
	(*Event)(nil),        // 10: xray.app.tariff.Event
	(*QuotaSpent)(nil),   // 11: xray.app.tariff.QuotaSpent
	(*UserState)(nil),    // 12: xray.app.tariff.UserState
	(*State)(nil),        // 13: xray.app.tariff.State
	(*Config)(nil),       // 14: xray.app.tariff.Config
	nil,                  // 15: xray.app.tariff.State.UsersEntry
}
var file_app_tariff_config_proto_depIdxs = []int32{
	0,  // 0: xray.app.tariff.Quota.window:type_name -> xray.app.tariff.Window
	1,  // 1: xray.app.tariff.Quota.action:type_name -> xray.app.tariff.Action
	1,  // 2: xray.app.tariff.Policy.device_limit_action:type_name -> xray.app.tariff.Action
	3,  // 3: xray.app.tariff.Policy.quotas:type_name -> xray.app.tariff.Quota
	0,  // 4: xray.app.tariff.ServerQuota.window:type_name -> xray.app.tariff.Window
	1,  // 5: xray.app.tariff.ServerQuota.action:type_name -> xray.app.tariff.Action
	0,  // 6: xray.app.tariff.QuotaState.window:type_name -> xray.app.tariff.Window
	1,  // 7: xray.app.tariff.QuotaState.action:type_name -> xray.app.tariff.Action
	8,  // 8: xray.app.tariff.Usage.inbounds:type_name -> xray.app.tariff.InboundUsage
	6,  // 9: xray.app.tariff.Usage.devices:type_name -> xray.app.tariff.Device
	7,  // 10: xray.app.tariff.Usage.quotas:type_name -> xray.app.tariff.QuotaState
	2,  // 11: xray.app.tariff.Event.kind:type_name -> xray.app.tariff.EventKind
	3,  // 12: xray.app.tariff.QuotaSpent.spec:type_name -> xray.app.tariff.Quota
	4,  // 13: xray.app.tariff.UserState.policy:type_name -> xray.app.tariff.Policy
	8,  // 14: xray.app.tariff.UserState.inbounds:type_name -> xray.app.tariff.InboundUsage
	11, // 15: xray.app.tariff.UserState.quotas:type_name -> xray.app.tariff.QuotaSpent
	14, // 16: xray.app.tariff.State.config:type_name -> xray.app.tariff.Config
	15, // 17: xray.app.tariff.State.users:type_name -> xray.app.tariff.State.UsersEntry
	5,  // 18: xray.app.tariff.State.server_quota:type_name -> xray.app.tariff.ServerQuota
	4,  // 19: xray.app.tariff.Config.default_policy:type_name -> xray.app.tariff.Policy
	5,  // 20: xray.app.tariff.Config.server_quota:type_name -> xray.app.tariff.ServerQuota
	12, // 21: xray.app.tariff.State.UsersEntry.value:type_name -> xray.app.tariff.UserState
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_app_tariff_config_proto_init() }
func file_app_tariff_config_proto_init() {
	if File_app_tariff_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_tariff_config_proto_rawDesc), len(file_app_tariff_config_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_tariff_config_proto_goTypes,
		DependencyIndexes: file_app_tariff_config_proto_depIdxs,
		EnumInfos:         file_app_tariff_config_proto_enumTypes,
		MessageInfos:      file_app_tariff_config_proto_msgTypes,
	}.Build()
	File_app_tariff_config_proto = out.File
	file_app_tariff_config_proto_goTypes = nil
	file_app_tariff_config_proto_depIdxs = nil
}
