// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: app/tariff/command/command.proto

package command

import (
	tariff "github.com/xtls/xray-core/app/tariff"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policy        *tariff.Policy         `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPolicyRequest) Reset() {
	*x = SetPolicyRequest{}
	mi := &file_app_tariff_command_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPolicyRequest) ProtoMessage() {}

func (x *SetPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_tariff_command_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPolicyRequest.ProtoReflect.Descriptor instead.
func (*SetPolicyRequest) Descriptor() ([]byte, []int) {
	return file_app_tariff_command_command_proto_rawDescGZIP(), []int{0}
}

func (x *SetPolicyRequest) GetPolicy() *tariff.Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

type SetPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPolicyResponse) Reset() {
	*x = SetPolicyResponse{}
	mi := &file_app_tariff_command_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPolicyResponse) ProtoMessage() {}

func (x *SetPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_tariff_command_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPolicyResponse.ProtoReflect.Descriptor instead.
func (*SetPolicyResponse) Descriptor() ([]byte, []int) {
	return file_app_tariff_command_command_proto_rawDescGZIP(), []int{1}
}

// SetPolicies pushes a whole roster at once.
//
// A panel that syncs periodically should use this with replace set: the server
// then converges on exactly the users given, dropping any it holds that are
// not in the list. That removes the need for the panel to work out what
// changed, and it means a user deleted while the server was unreachable does
// not survive forever.
type SetPoliciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policies      []*tariff.Policy       `protobuf:"bytes,1,rep,name=policies,proto3" json:"policies,omitempty"`
	Replace       bool                   `protobuf:"varint,2,opt,name=replace,proto3" json:"replace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPoliciesRequest) Reset() {
	*x = SetPoliciesRequest{}
	mi := &file_app_tariff_command_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPoliciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPoliciesRequest) ProtoMessage() {}

func (x *SetPoliciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_tariff_command_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPoliciesRequest.ProtoReflect.Descriptor instead.
func (*SetPoliciesRequest) Descriptor() ([]byte, []int) {
	return file_app_tariff_command_command_proto_rawDescGZIP(), []int{2}
}

func (x *SetPoliciesRequest) GetPolicies() []*tariff.Policy {
	if x != nil {
		return x.Policies
	}
	return nil
}

func (x *SetPoliciesRequest) GetReplace() bool {
	if x != nil {
		return x.Replace
	}
	return false
}

type SetPoliciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Applied       uint32                 `protobuf:"varint,1,opt,name=applied,proto3" json:"applied,omitempty"`
	Removed       uint32                 `protobuf:"varint,2,opt,name=removed,proto3" json:"removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPoliciesResponse) Reset() {
	*x = SetPoliciesResponse{}
	mi := &file_app_tariff_command_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPoliciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPoliciesResponse) ProtoMessage() {}

func (x *SetPoliciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_tariff_command_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPoliciesResponse.ProtoReflect.Descriptor instead.
func (*SetPoliciesResponse) Descriptor() ([]byte, []int) {
	return file_app_tariff_command_command_proto_rawDescGZIP(), []int{3}
}

func (x *SetPoliciesResponse) GetApplied() uint32 {
	if x != nil {
		return x.Applied
	}
	return 0
}

func (x *SetPoliciesResponse) GetRemoved() uint32 {
	if x != nil {
		return x.Removed
	}
	return 0
}

type GetPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPolicyRequest) Reset() {
	*x = GetPolicyRequest{}
	mi := &file_app_tariff_command_command_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPolicyRequest) ProtoMessage() {}

func (x *GetPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_tariff_command_command_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPolicyRequest.ProtoReflect.Descriptor instead.
func (*GetPolicyRequest) Descriptor() ([]byte, []int) {
	return file_app_tariff_command_command_proto_rawDescGZIP(), []int{4}
}

func (x *GetPolicyRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policy        *tariff.Policy         `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPolicyResponse) Reset() {
	*x = GetPolicyResponse{}
	mi := &file_app_tariff_command_command_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPolicyResponse) ProtoMessage() {}

func (x *GetPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_tariff_command_command_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPolicyResponse.ProtoReflect.Descriptor instead.
func (*GetPolicyResponse) Descriptor() ([]byte, []int) {
	return file_app_tariff_command_command_proto_rawDescGZIP(), []int{5}
}

func (x *GetPolicyResponse) GetPolicy() *tariff.Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

type RemovePolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePolicyRequest) Reset() {
	*x = RemovePolicyRequest{}
	mi := &file_app_tariff_command_command_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePolicyRequest) ProtoMessage() {}

func (x *RemovePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_tariff_command_command_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePolicyRequest.ProtoReflect.Descriptor instead.
func (*RemovePolicyRequest) Descriptor() ([]byte, []int) {
	return file_app_tariff_command_command_proto_rawDescGZIP(), []int{6}
}

func (x *RemovePolicyRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type RemovePolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePolicyResponse) Reset() {
	*x = RemovePolicyResponse{}
	mi := &file_app_tariff_command_command_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePolicyResponse) ProtoMessage() {}

func (x *RemovePolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_tariff_command_command_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePolicyResponse.ProtoReflect.Descriptor instead.
func (*RemovePolicyResponse) Descriptor() ([]byte, []int) {
	return file_app_tariff_command_command_proto_rawDescGZIP(), []int{7}
}

type ListPoliciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoliciesRequest) Reset() {
	*x = ListPoliciesRequest{}
	mi := &file_app_tariff_command_command_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoliciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoliciesRequest) ProtoMessage() {}

func (x *ListPoliciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_tariff_command_command_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoliciesRequest.ProtoReflect.Descriptor instead.
func (*ListPoliciesRequest) Descriptor() ([]byte, []int) {
	return file_app_tariff_command_command_proto_rawDescGZIP(), []int{8}
}

type ListPoliciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policies      []*tariff.Policy       `protobuf:"bytes,1,rep,name=policies,proto3" json:"policies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoliciesResponse) Reset() {
	*x = ListPoliciesResponse{}
	mi := &file_app_tariff_command_command_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoliciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoliciesResponse) ProtoMessage() {}

func (x *ListPoliciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_tariff_command_command_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoliciesResponse.ProtoReflect.Descriptor instead.
func (*ListPoliciesResponse) Descriptor() ([]byte, []int) {
	return file_app_tariff_command_command_proto_rawDescGZIP(), []int{9}
}

func (x *ListPoliciesResponse) GetPolicies() []*tariff.Policy {
	if x != nil {
		return x.Policies
	}
	return nil
}

// GetUsage reports what users have spent. An empty email returns everyone.
type GetUsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsageRequest) Reset() {
	*x = GetUsageRequest{}
	mi := &file_app_tariff_command_command_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsageRequest) ProtoMessage() {}

func (x *GetUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_tariff_command_command_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsageRequest.ProtoReflect.Descriptor instead.
func (*GetUsageRequest) Descriptor() ([]byte, []int) {
	return file_app_tariff_command_command_proto_rawDescGZIP(), []int{10}
}

func (x *GetUsageRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetUsageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*tariff.Usage        `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsageResponse) Reset() {
	*x = GetUsageResponse{}
	mi := &file_app_tariff_command_command_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsageResponse) ProtoMessage() {}

func (x *GetUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_tariff_command_command_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsageResponse.ProtoReflect.Descriptor instead.
func (*GetUsageResponse) Descriptor() ([]byte, []int) {
	return file_app_tariff_command_command_proto_rawDescGZIP(), []int{11}
}

func (x *GetUsageResponse) GetUsers() []*tariff.Usage {
	if x != nil {
		return x.Users
	}
	return nil
}

// AddUsage adds to a user's counters without any traffic having crossed this
// server, for restoring a month-to-date figure after a state file is lost or a
// subscription moves between servers. An empty inbound_tag adds to the total
// without attributing it to any inbound.
type AddUsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	InboundTag    string                 `protobuf:"bytes,2,opt,name=inbound_tag,json=inboundTag,proto3" json:"inbound_tag,omitempty"`
	Uplink        uint64                 `protobuf:"varint,3,opt,name=uplink,proto3" json:"uplink,omitempty"`
	Downlink      uint64                 `protobuf:"varint,4,opt,name=downlink,proto3" json:"downlink,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUsageRequest) Reset() {
	*x = AddUsageRequest{}
	mi := &file_app_tariff_command_command_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUsageRequest) ProtoMessage() {}

func (x *AddUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_tariff_command_command_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUsageRequest.ProtoReflect.Descriptor instead.
func (*AddUsageRequest) Descriptor() ([]byte, []int) {
	return file_app_tariff_command_command_proto_rawDescGZIP(), []int{12}
}

func (x *AddUsageRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AddUsageRequest) GetInboundTag() string {
	if x != nil {
		return x.InboundTag
	}
	return ""
}

func (x *AddUsageRequest) GetUplink() uint64 {
	if x != nil {
		return x.Uplink
	}
	return 0
}

func (x *AddUsageRequest) GetDownlink() uint64 {
	if x != nil {
		return x.Downlink
	}
	return 0
}

type AddUsageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUsageResponse) Reset() {
	*x = AddUsageResponse{}
	mi := &file_app_tariff_command_command_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUsageResponse) ProtoMessage() {}

func (x *AddUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_tariff_command_command_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUsageResponse.ProtoReflect.Descriptor instead.
func (*AddUsageResponse) Descriptor() ([]byte, []int) {
	return file_app_tariff_command_command_proto_rawDescGZIP(), []int{13}
}

// ResetUsage clears a user's counters and re-arms their quotas. An empty email
// resets the server-wide allowance instead.
type ResetUsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetUsageRequest) Reset() {
	*x = ResetUsageRequest{}
	mi := &file_app_tariff_command_command_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetUsageRequest) ProtoMessage() {}

func (x *ResetUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_tariff_command_command_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetUsageRequest.ProtoReflect.Descriptor instead.
func (*ResetUsageRequest) Descriptor() ([]byte, []int) {
	return file_app_tariff_command_command_proto_rawDescGZIP(), []int{14}
}

func (x *ResetUsageRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ResetUsageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetUsageResponse) Reset() {
	*x = ResetUsageResponse{}
	mi := &file_app_tariff_command_command_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetUsageResponse) ProtoMessage() {}

func (x *ResetUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_tariff_command_command_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetUsageResponse.ProtoReflect.Descriptor instead.
func (*ResetUsageResponse) Descriptor() ([]byte, []int) {
	return file_app_tariff_command_command_proto_rawDescGZIP(), []int{15}
}

type SetServerQuotaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quota         *tariff.ServerQuota    `protobuf:"bytes,1,opt,name=quota,proto3" json:"quota,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetServerQuotaRequest) Reset() {
	*x = SetServerQuotaRequest{}
	mi := &file_app_tariff_command_command_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetServerQuotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetServerQuotaRequest) ProtoMessage() {}

func (x *SetServerQuotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_tariff_command_command_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetServerQuotaRequest.ProtoReflect.Descriptor instead.
func (*SetServerQuotaRequest) Descriptor() ([]byte, []int) {
	return file_app_tariff_command_command_proto_rawDescGZIP(), []int{16}
}

func (x *SetServerQuotaRequest) GetQuota() *tariff.ServerQuota {
	if x != nil {
		return x.Quota
	}
	return nil
}

type SetServerQuotaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetServerQuotaResponse) Reset() {
	*x = SetServerQuotaResponse{}
	mi := &file_app_tariff_command_command_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetServerQuotaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetServerQuotaResponse) ProtoMessage() {}

func (x *SetServerQuotaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_tariff_command_command_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetServerQuotaResponse.ProtoReflect.Descriptor instead.
func (*SetServerQuotaResponse) Descriptor() ([]byte, []int) {
	return file_app_tariff_command_command_proto_rawDescGZIP(), []int{17}
}

type SetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *tariff.Config         `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConfigRequest) Reset() {
	*x = SetConfigRequest{}
	mi := &file_app_tariff_command_command_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConfigRequest) ProtoMessage() {}

func (x *SetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_tariff_command_command_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConfigRequest.ProtoReflect.Descriptor instead.
func (*SetConfigRequest) Descriptor() ([]byte, []int) {
	return file_app_tariff_command_command_proto_rawDescGZIP(), []int{18}
}

func (x *SetConfigRequest) GetConfig() *tariff.Config {
	if x != nil {
		return x.Config
	}
	return nil
}

type SetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConfigResponse) Reset() {
	*x = SetConfigResponse{}
	mi := &file_app_tariff_command_command_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConfigResponse) ProtoMessage() {}

func (x *SetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_tariff_command_command_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConfigResponse.ProtoReflect.Descriptor instead.
func (*SetConfigResponse) Descriptor() ([]byte, []int) {
	return file_app_tariff_command_command_proto_rawDescGZIP(), []int{19}
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_app_tariff_command_command_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_tariff_command_command_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_app_tariff_command_command_proto_rawDescGZIP(), []int{20}
}

type GetStatusResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Users            uint32                 `protobuf:"varint,1,opt,name=users,proto3" json:"users,omitempty"`
	Connections      uint32                 `protobuf:"varint,2,opt,name=connections,proto3" json:"connections,omitempty"`
	Devices          uint32                 `protobuf:"varint,3,opt,name=devices,proto3" json:"devices,omitempty"`
	EventSubscribers uint32                 `protobuf:"varint,4,opt,name=event_subscribers,json=eventSubscribers,proto3" json:"event_subscribers,omitempty"`
	ServerQuota      *tariff.QuotaState     `protobuf:"bytes,5,opt,name=server_quota,json=serverQuota,proto3" json:"server_quota,omitempty"`
	Config           *tariff.Config         `protobuf:"bytes,6,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_app_tariff_command_command_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_tariff_command_command_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_app_tariff_command_command_proto_rawDescGZIP(), []int{21}
}

func (x *GetStatusResponse) GetUsers() uint32 {
	if x != nil {
		return x.Users
	}
	return 0
}

func (x *GetStatusResponse) GetConnections() uint32 {
	if x != nil {
		return x.Connections
	}
	return 0
}

func (x *GetStatusResponse) GetDevices() uint32 {
	if x != nil {
		return x.Devices
	}
	return 0
}

func (x *GetStatusResponse) GetEventSubscribers() uint32 {
	if x != nil {
		return x.EventSubscribers
	}
	return 0
}

func (x *GetStatusResponse) GetServerQuota() *tariff.QuotaState {
	if x != nil {
		return x.ServerQuota
	}
	return nil
}

func (x *GetStatusResponse) GetConfig() *tariff.Config {
	if x != nil {
		return x.Config
	}
	return nil
}

// Flush writes the state file immediately rather than waiting for the next
// periodic write. Worth calling before a planned restart.
type FlushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushRequest) Reset() {
	*x = FlushRequest{}
	mi := &file_app_tariff_command_command_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushRequest) ProtoMessage() {}

func (x *FlushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_tariff_command_command_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushRequest.ProtoReflect.Descriptor instead.
func (*FlushRequest) Descriptor() ([]byte, []int) {
	return file_app_tariff_command_command_proto_rawDescGZIP(), []int{22}
}

type FlushResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushResponse) Reset() {
	*x = FlushResponse{}
	mi := &file_app_tariff_command_command_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushResponse) ProtoMessage() {}

func (x *FlushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_tariff_command_command_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushResponse.ProtoReflect.Descriptor instead.
func (*FlushResponse) Descriptor() ([]byte, []int) {
	return file_app_tariff_command_command_proto_rawDescGZIP(), []int{23}
}

// StreamEvents delivers changes as they happen, so a panel does not have to
// poll to find out that a user went over their quota or connected from a new
// device.
//
// A stream that stops being read loses events rather than applying
// back-pressure to the data plane; dropped counts how many this stream has
// missed since it started, so a client that cares can reconcile with GetUsage.
type StreamEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Only these kinds. Empty means every kind.
	Kinds []tariff.EventKind `protobuf:"varint,1,rep,packed,name=kinds,proto3,enum=xray.app.tariff.EventKind" json:"kinds,omitempty"`
	// Only this user. Empty means every user.
	Email         string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_app_tariff_command_command_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_tariff_command_command_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_app_tariff_command_command_proto_rawDescGZIP(), []int{24}
}

func (x *StreamEventsRequest) GetKinds() []tariff.EventKind {
	if x != nil {
		return x.Kinds
	}
	return nil
}

func (x *StreamEventsRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type StreamEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *tariff.Event          `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Dropped       uint64                 `protobuf:"varint,2,opt,name=dropped,proto3" json:"dropped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsResponse) Reset() {
	*x = StreamEventsResponse{}
	mi := &file_app_tariff_command_command_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsResponse) ProtoMessage() {}

func (x *StreamEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_tariff_command_command_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsResponse.ProtoReflect.Descriptor instead.
func (*StreamEventsResponse) Descriptor() ([]byte, []int) {
	return file_app_tariff_command_command_proto_rawDescGZIP(), []int{25}
}

func (x *StreamEventsResponse) GetEvent() *tariff.Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *StreamEventsResponse) GetDropped() uint64 {
	if x != nil {
		return x.Dropped
	}
	return 0
}

// Config is the service's own configuration, named in the API's service list.
type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_app_tariff_command_command_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_app_tariff_command_command_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_app_tariff_command_command_proto_rawDescGZIP(), []int{26}
}

var File_app_tariff_command_command_proto protoreflect.FileDescriptor

const file_app_tariff_command_command_proto_rawDesc = "" +
	"\n" +
	" app/tariff/command/command.proto\x12\x17xray.app.tariff.command\x1a\x17app/tariff/config.proto\"C\n" +
	"\x10SetPolicyRequest\x12/\n" +
	"\x06policy\x18\x01 \x01(\v2\x17.xray.app.tariff.PolicyR\x06policy\"\x13\n" +
	"\x11SetPolicyResponse\"c\n" +
	"\x12SetPoliciesRequest\x123\n" +
	"\bpolicies\x18\x01 \x03(\v2\x17.xray.app.tariff.PolicyR\bpolicies\x12\x18\n" +
	"\areplace\x18\x02 \x01(\bR\areplace\"I\n" +
	"\x13SetPoliciesResponse\x12\x18\n" +
	"\aapplied\x18\x01 \x01(\rR\aapplied\x12\x18\n" +
	"\aremoved\x18\x02 \x01(\rR\aremoved\"(\n" +
	"\x10GetPolicyRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"D\n" +
	"\x11GetPolicyResponse\x12/\n" +
	"\x06policy\x18\x01 \x01(\v2\x17.xray.app.tariff.PolicyR\x06policy\"+\n" +
	"\x13RemovePolicyRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"\x16\n" +
	"\x14RemovePolicyResponse\"\x15\n" +
	"\x13ListPoliciesRequest\"K\n" +
	"\x14ListPoliciesResponse\x123\n" +
	"\bpolicies\x18\x01 \x03(\v2\x17.xray.app.tariff.PolicyR\bpolicies\"'\n" +
	"\x0fGetUsageRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"@\n" +
	"\x10GetUsageResponse\x12,\n" +
	"\x05users\x18\x01 \x03(\v2\x16.xray.app.tariff.UsageR\x05users\"|\n" +
	"\x0fAddUsageRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1f\n" +
	"\vinbound_tag\x18\x02 \x01(\tR\n" +
	"inboundTag\x12\x16\n" +
	"\x06uplink\x18\x03 \x01(\x04R\x06uplink\x12\x1a\n" +
	"\bdownlink\x18\x04 \x01(\x04R\bdownlink\"\x12\n" +
	"\x10AddUsageResponse\")\n" +
	"\x11ResetUsageRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"\x14\n" +
	"\x12ResetUsageResponse\"K\n" +
	"\x15SetServerQuotaRequest\x122\n" +
	"\x05quota\x18\x01 \x01(\v2\x1c.xray.app.tariff.ServerQuotaR\x05quota\"\x18\n" +
	"\x16SetServerQuotaResponse\"C\n" +
	"\x10SetConfigRequest\x12/\n" +
	"\x06config\x18\x01 \x01(\v2\x17.xray.app.tariff.ConfigR\x06config\"\x13\n" +
	"\x11SetConfigResponse\"\x12\n" +
	"\x10GetStatusRequest\"\x83\x02\n" +
	"\x11GetStatusResponse\x12\x14\n" +
	"\x05users\x18\x01 \x01(\rR\x05users\x12 \n" +
	"\vconnections\x18\x02 \x01(\rR\vconnections\x12\x18\n" +
	"\adevices\x18\x03 \x01(\rR\adevices\x12+\n" +
	"\x11event_subscribers\x18\x04 \x01(\rR\x10eventSubscribers\x12>\n" +
	"\fserver_quota\x18\x05 \x01(\v2\x1b.xray.app.tariff.QuotaStateR\vserverQuota\x12/\n" +
	"\x06config\x18\x06 \x01(\v2\x17.xray.app.tariff.ConfigR\x06config\"\x0e\n" +
	"\fFlushRequest\"\x0f\n" +
	"\rFlushResponse\"]\n" +
	"\x13StreamEventsRequest\x120\n" +
	"\x05kinds\x18\x01 \x03(\x0e2\x1a.xray.app.tariff.EventKindR\x05kinds\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"^\n" +
	"\x14StreamEventsResponse\x12,\n" +
	"\x05event\x18\x01 \x01(\v2\x16.xray.app.tariff.EventR\x05event\x12\x18\n" +
	"\adropped\x18\x02 \x01(\x04R\adropped\"\b\n" +
	"\x06Config2\xe0\n" +
	"\n" +
	"\rTariffService\x12d\n" +
	"\tSetPolicy\x12).xray.app.tariff.command.SetPolicyRequest\x1a*.xray.app.tariff.command.SetPolicyResponse\"\x00\x12j\n" +
	"\vSetPolicies\x12+.xray.app.tariff.command.SetPoliciesRequest\x1a,.xray.app.tariff.command.SetPoliciesResponse\"\x00\x12d\n" +
	"\tGetPolicy\x12).xray.app.tariff.command.GetPolicyRequest\x1a*.xray.app.tariff.command.GetPolicyResponse\"\x00\x12m\n" +
	"\fRemovePolicy\x12,.xray.app.tariff.command.RemovePolicyRequest\x1a-.xray.app.tariff.command.RemovePolicyResponse\"\x00\x12m\n" +
	"\fListPolicies\x12,.xray.app.tariff.command.ListPoliciesRequest\x1a-.xray.app.tariff.command.ListPoliciesResponse\"\x00\x12a\n" +
	"\bGetUsage\x12(.xray.app.tariff.command.GetUsageRequest\x1a).xray.app.tariff.command.GetUsageResponse\"\x00\x12a\n" +
	"\bAddUsage\x12(.xray.app.tariff.command.AddUsageRequest\x1a).xray.app.tariff.command.AddUsageResponse\"\x00\x12g\n" +
	"\n" +
	"ResetUsage\x12*.xray.app.tariff.command.ResetUsageRequest\x1a+.xray.app.tariff.command.ResetUsageResponse\"\x00\x12s\n" +
	"\x0eSetServerQuota\x12..xray.app.tariff.command.SetServerQuotaRequest\x1a/.xray.app.tariff.command.SetServerQuotaResponse\"\x00\x12d\n" +
	"\tSetConfig\x12).xray.app.tariff.command.SetConfigRequest\x1a*.xray.app.tariff.command.SetConfigResponse\"\x00\x12d\n" +
	"\tGetStatus\x12).xray.app.tariff.command.GetStatusRequest\x1a*.xray.app.tariff.command.GetStatusResponse\"\x00\x12X\n" +
	"\x05Flush\x12%.xray.app.tariff.command.FlushRequest\x1a&.xray.app.tariff.command.FlushResponse\"\x00\x12o\n" +
	"\fStreamEvents\x12,.xray.app.tariff.command.StreamEventsRequest\x1a-.xray.app.tariff.command.StreamEventsResponse\"\x000\x01Bg\n" +
	"\x1bcom.xray.app.tariff.commandP\x01Z,github.com/xtls/xray-core/app/tariff/command\xaa\x02\x17Xray.App.Tariff.Commandb\x06proto3"

var (
	file_app_tariff_command_command_proto_rawDescOnce sync.Once
	file_app_tariff_command_command_proto_rawDescData []byte
)

func file_app_tariff_command_command_proto_rawDescGZIP() []byte {
	file_app_tariff_command_command_proto_rawDescOnce.Do(func() {
		file_app_tariff_command_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_tariff_command_command_proto_rawDesc), len(file_app_tariff_command_command_proto_rawDesc)))
	})
	return file_app_tariff_command_command_proto_rawDescData
}

var file_app_tariff_command_command_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_app_tariff_command_command_proto_goTypes = []any{
	(*SetPolicyRequest)(nil),       // 0: xray.app.tariff.command.SetPolicyRequest
	(*SetPolicyResponse)(nil),      // 1: xray.app.tariff.command.SetPolicyResponse
	(*SetPoliciesRequest)(nil),     // 2: xray.app.tariff.command.SetPoliciesRequest
	(*SetPoliciesResponse)(nil),    // 3: xray.app.tariff.command.SetPoliciesResponse
	(*GetPolicyRequest)(nil),       // 4: xray.app.tariff.command.GetPolicyRequest
	(*GetPolicyResponse)(nil),      // 5: xray.app.tariff.command.GetPolicyResponse
	(*RemovePolicyRequest)(nil),    // 6: xray.app.tariff.command.RemovePolicyRequest
	(*RemovePolicyResponse)(nil),   // 7: xray.app.tariff.command.RemovePolicyResponse
	(*ListPoliciesRequest)(nil),    // 8: xray.app.tariff.command.ListPoliciesRequest
	(*ListPoliciesResponse)(nil),   // 9: xray.app.tariff.command.ListPoliciesResponse
	(*GetUsageRequest)(nil),        // 10: xray.app.tariff.command.GetUsageRequest
	(*GetUsageResponse)(nil),       // 11: xray.app.tariff.command.GetUsageResponse
	(*AddUsageRequest)(nil),        // 12: xray.app.tariff.command.AddUsageRequest
	(*AddUsageResponse)(nil),       // 13: xray.app.tariff.command.AddUsageResponse
	(*ResetUsageRequest)(nil),      // 14: xray.app.tariff.command.ResetUsageRequest
	(*ResetUsageResponse)(nil),     // 15: xray.app.tariff.command.ResetUsageResponse
	(*SetServerQuotaRequest)(nil),  // 16: xray.app.tariff.command.SetServerQuotaRequest
	(*SetServerQuotaResponse)(nil), // 17: xray.app.tariff.command.SetServerQuotaResponse
	(*SetConfigRequest)(nil),       // 18: xray.app.tariff.command.SetConfigRequest
	(*SetConfigResponse)(nil),      // 19: xray.app.tariff.command.SetConfigResponse
	(*GetStatusRequest)(nil),       // 20: xray.app.tariff.command.GetStatusRequest
	(*GetStatusResponse)(nil),      // 21: xray.app.tariff.command.GetStatusResponse
	(*FlushRequest)(nil),           // 22: xray.app.tariff.command.FlushRequest
	(*FlushResponse)(nil),          // 23: xray.app.tariff.command.FlushResponse
	(*StreamEventsRequest)(nil),    // 24: xray.app.tariff.command.StreamEventsRequest
	(*StreamEventsResponse)(nil),   // 25: xray.app.tariff.command.StreamEventsResponse
	(*Config)(nil),                 // 26: xray.app.tariff.command.Config
	(*tariff.Policy)(nil),          // 27: xray.app.tariff.Policy
	(*tariff.Usage)(nil),           // 28: xray.app.tariff.Usage
	(*tariff.ServerQuota)(nil),     // 29: xray.app.tariff.ServerQuota
	(*tariff.Config)(nil),          // 30: xray.app.tariff.Config
	(*tariff.QuotaState)(nil),      // 31: xray.app.tariff.QuotaState
	(tariff.EventKind)(0),          // 32: xray.app.tariff.EventKind
	(*tariff.Event)(nil),           // 33: xray.app.tariff.Event
}
var file_app_tariff_command_command_proto_depIdxs = []int32{
	27, // 0: xray.app.tariff.command.SetPolicyRequest.policy:type_name -> xray.app.tariff.Policy
	27, // 1: xray.app.tariff.command.SetPoliciesRequest.policies:type_name -> xray.app.tariff.Policy
	27, // 2: xray.app.tariff.command.GetPolicyResponse.policy:type_name -> xray.app.tariff.Policy
	27, // 3: xray.app.tariff.command.ListPoliciesResponse.policies:type_name -> xray.app.tariff.Policy
	28, // 4: xray.app.tariff.command.GetUsageResponse.users:type_name -> xray.app.tariff.Usage
	29, // 5: xray.app.tariff.command.SetServerQuotaRequest.quota:type_name -> xray.app.tariff.ServerQuota
	30, // 6: xray.app.tariff.command.SetConfigRequest.config:type_name -> xray.app.tariff.Config
	31, // 7: xray.app.tariff.command.GetStatusResponse.server_quota:type_name -> xray.app.tariff.QuotaState
	30, // 8: xray.app.tariff.command.GetStatusResponse.config:type_name -> xray.app.tariff.Config
	32, // 9: xray.app.tariff.command.StreamEventsRequest.kinds:type_name -> xray.app.tariff.EventKind
	33, // 10: xray.app.tariff.command.StreamEventsResponse.event:type_name -> xray.app.tariff.Event
	0,  // 11: xray.app.tariff.command.TariffService.SetPolicy:input_type -> xray.app.tariff.command.SetPolicyRequest
	2,  // 12: xray.app.tariff.command.TariffService.SetPolicies:input_type -> xray.app.tariff.command.SetPoliciesRequest
	4,  // 13: xray.app.tariff.command.TariffService.GetPolicy:input_type -> xray.app.tariff.command.GetPolicyRequest
	6,  // 14: xray.app.tariff.command.TariffService.RemovePolicy:input_type -> xray.app.tariff.command.RemovePolicyRequest
	8,  // 15: xray.app.tariff.command.TariffService.ListPolicies:input_type -> xray.app.tariff.command.ListPoliciesRequest
	10, // 16: xray.app.tariff.command.TariffService.GetUsage:input_type -> xray.app.tariff.command.GetUsageRequest
	12, // 17: xray.app.tariff.command.TariffService.AddUsage:input_type -> xray.app.tariff.command.AddUsageRequest
	14, // 18: xray.app.tariff.command.TariffService.ResetUsage:input_type -> xray.app.tariff.command.ResetUsageRequest
	16, // 19: xray.app.tariff.command.TariffService.SetServerQuota:input_type -> xray.app.tariff.command.SetServerQuotaRequest
	18, // 20: xray.app.tariff.command.TariffService.SetConfig:input_type -> xray.app.tariff.command.SetConfigRequest
	20, // 21: xray.app.tariff.command.TariffService.GetStatus:input_type -> xray.app.tariff.command.GetStatusRequest
	22, // 22: xray.app.tariff.command.TariffService.Flush:input_type -> xray.app.tariff.command.FlushRequest
	24, // 23: xray.app.tariff.command.TariffService.StreamEvents:input_type -> xray.app.tariff.command.StreamEventsRequest
	1,  // 24: xray.app.tariff.command.TariffService.SetPolicy:output_type -> xray.app.tariff.command.SetPolicyResponse
	3,  // 25: xray.app.tariff.command.TariffService.SetPolicies:output_type -> xray.app.tariff.command.SetPoliciesResponse
	5,  // 26: xray.app.tariff.command.TariffService.GetPolicy:output_type -> xray.app.tariff.command.GetPolicyResponse
	7,  // 27: xray.app.tariff.command.TariffService.RemovePolicy:output_type -> xray.app.tariff.command.RemovePolicyResponse
	9,  // 28: xray.app.tariff.command.TariffService.ListPolicies:output_type -> xray.app.tariff.command.ListPoliciesResponse
	11, // 29: xray.app.tariff.command.TariffService.GetUsage:output_type -> xray.app.tariff.command.GetUsageResponse
	13, // 30: xray.app.tariff.command.TariffService.AddUsage:output_type -> xray.app.tariff.command.AddUsageResponse
	15, // 31: xray.app.tariff.command.TariffService.ResetUsage:output_type -> xray.app.tariff.command.ResetUsageResponse
	17, // 32: xray.app.tariff.command.TariffService.SetServerQuota:output_type -> xray.app.tariff.command.SetServerQuotaResponse
	19, // 33: xray.app.tariff.command.TariffService.SetConfig:output_type -> xray.app.tariff.command.SetConfigResponse
	21, // 34: xray.app.tariff.command.TariffService.GetStatus:output_type -> xray.app.tariff.command.GetStatusResponse
	23, // 35: xray.app.tariff.command.TariffService.Flush:output_type -> xray.app.tariff.command.FlushResponse
	25, // 36: xray.app.tariff.command.TariffService.StreamEvents:output_type -> xray.app.tariff.command.StreamEventsResponse
	24, // [24:37] is the sub-list for method output_type
	11, // [11:24] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_app_tariff_command_command_proto_init() }
func file_app_tariff_command_command_proto_init() {
	if File_app_tariff_command_command_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_tariff_command_command_proto_rawDesc), len(file_app_tariff_command_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_tariff_command_command_proto_goTypes,
		DependencyIndexes: file_app_tariff_command_command_proto_depIdxs,
		MessageInfos:      file_app_tariff_command_command_proto_msgTypes,
	}.Build()
	File_app_tariff_command_command_proto = out.File
	file_app_tariff_command_command_proto_goTypes = nil
	file_app_tariff_command_command_proto_depIdxs = nil
}
